kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: postgres-pgbench-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "2"
  priority_io: "high"
allowVolumeExpansion: true
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pgbench-data
  namespace: pgbench
  labels:
    name: pgbench-data
  annotations:
   torpedo.io/autopilot-enabled: "true"
   #torpedo.io/autopilot-pvc-resize-enabled: "true"
   torpedo.io/autopilot-storage-pool-resize-enabled: "true"
spec:
  storageClassName: postgres-pgbench-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pgbench-state
  namespace: pgbench
spec:
  storageClassName: postgres-pgbench-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
